//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoCommons.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoCommons.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0001	OSLO	0301	OSLO	K
        ///0010	OSLO	0301	OSLO	F
        ///0014	OSLO	0301	OSLO	K
        ///0015	OSLO	0301	OSLO	K
        ///0016	OSLO	0301	OSLO	K
        ///0017	OSLO	0301	OSLO	K
        ///0018	OSLO	0301	OSLO	G
        ///0020	OSLO	0301	OSLO	K
        ///0021	OSLO	0301	OSLO	K
        ///0022	OSLO	0301	OSLO	K
        ///0023	OSLO	0301	OSLO	F
        ///0024	OSLO	0301	OSLO	K
        ///0025	OSLO	0301	OSLO	K
        ///0026	OSLO	0301	OSLO	F
        ///0027	OSLO	0301	OSLO	F
        ///0028	OSLO	0301	OSLO	P
        ///0030	OSLO	0301	OSLO	P
        ///0031	OSLO	0301	OSLO	P
        ///0032	OSLO	0301	OSLO	P
        ///0033	OSLO	0301	OSLO	P
        ///0034	OSLO	0301	OSLO	P
        ///0037	OSLO	0301	OSLO	K
        ///0040	O [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tilbud5 {
            get {
                return ResourceManager.GetString("tilbud5", resourceCulture);
            }
        }
    }
}
